on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  create:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions: write-all

jobs:
  build:
    if: always()
    runs-on: ubuntu-latest
    strategy:
      matrix:
        boards:
          - boardname: supermini_uf2/nrf52840/i2c
            fileformat: uf2
            filename: SlimeNRF_SuperMini_I2C_Tracker
          - boardname: supermini_uf2/nrf52840/spi
            fileformat: uf2
            filename: SlimeNRF_SuperMini_SPI_Tracker
          - boardname: xiao_ble/nrf52840
            fileformat: uf2
            filename: SlimeNRF_XIAO_Tracker
          - boardname: xiao_ble/nrf52840/sense
            fileformat: uf2
            filename: SlimeNRF_XIAO_Sense_Tracker
          - boardname: slimenrf_r1/nrf52840
            fileformat: hex
            filename: SlimeNRF_slimenrf_r1_Tracker
          - boardname: slimenrf_r2/nrf52832
            fileformat: hex
            filename: SlimeNRF_slimenrf_r2_Tracker
          - boardname: slimenrf_r3/nrf52840/uf2
            fileformat: uf2
            filename: SlimeNRF_slimenrf_r3_Tracker
          - boardname: slimevrmini_p1_uf2/nrf52833
            fileformat: uf2
            filename: SlimeNRF_slimevrmini_p1_Tracker
          - boardname: slimevrmini_p2_uf2/nrf52833
            fileformat: uf2
            filename: SlimeNRF_slimevrmini_p2_Tracker
          - boardname: slimevrmini_p3r6_uf2/nrf52833
            fileformat: uf2
            filename: SlimeNRF_slimevrmini_p3_r6_Tracker
          - boardname: slimevrmini_p3r7_uf2/nrf52833
            fileformat: uf2
            filename: SlimeNRF_slimevrmini_p3_r7_Tracker
          - boardname: nrf52dk/nrf52832
            fileformat: hex
            filename: SlimeNRF_nRF52dk_Tracker
          - boardname: nrf52840dk/nrf52840
            fileformat: hex
            filename: SlimeNRF_nRF52840dk_Tracker

    steps:
      - name: 🧹 Clean Landing Site
        run: sudo rm -rf zephyr-workspace/SlimeNRF-CI

      - uses: actions/checkout@v4
        with:
          path: zephyr-workspace/SlimeNRF-CI

      - name: 🔄 Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('zephyr/scripts/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: 🧰 Install Dependencies + West
        run: |
          sudo apt-get update && sudo apt install --no-install-recommends \
            git cmake ninja-build gperf ccache dfu-util device-tree-compiler \
            wget python3-dev python3-pip python3-setuptools python3-tk \
            python3-wheel python3-venv xz-utils file make gcc gcc-multilib \
            g++-multilib libsdl2-dev libmagic1
          python3 -m venv ~/.venv
          source ~/.venv/bin/activate
          echo "PATH=$PATH" >> $GITHUB_ENV
          pip3 install west ninja

      - name: 🔄 Cache Zephyr SDK
        uses: actions/cache@v3
        with:
          path: ~/zephyr-sdk-0.17.0
          key: ${{ runner.os }}-zephyr-sdk-v0.17.0
          restore-keys: |
            ${{ runner.os }}-zephyr-sdk-

      - name: 🪁 Install Zephyr SDK
        run: |
          if [ ! -d "${HOME}/zephyr-sdk-0.17.0" ]; then
            wget -q https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.17.0/zephyr-sdk-0.17.0_linux-x86_64_minimal.tar.xz
            tar xf zephyr-sdk-0.17.0_linux-x86_64_minimal.tar.xz -C ~/
            ~/zephyr-sdk-0.17.0/setup.sh -c -t arm-zephyr-eabi
          fi

      - name: 📂 Cloning Triggered Repository/Branch
        run: |
          cd zephyr-workspace
          git clone --single-branch --recurse-submodules -b $GITHUB_REF_NAME $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.git

      - name: ♻️ Initialize Zephyr Workspace
        run: |
          cd zephyr-workspace
          sudo rm -rf .west
          west init -l SlimeNRF-CI
          west update --narrow -o=--depth=1
          west zephyr-export

      - name: 🐍 Install Python Dependencies
        run: |
          cd zephyr-workspace
          pip3 install -r zephyr/scripts/requirements.txt

      - name: 🔨 Build SlimeVR-Tracker - ${{ matrix.boards.boardname }}
        run: |
          cd zephyr-workspace
          find='.dt_size\s=\sDT_REG_SIZE(DT_PARENT(node_id))}'
          replace='.dt_size = DT_REG_SIZE(DT_PARENT(node_id))},'
          sed -i "s/$find/$replace/g" zephyr/drivers/retained_mem/retained_mem_nrf_ram_ctrl.c
          sudo rm -rf Releases
          mkdir Releases
          sudo rm -rf ${{ github.event.repository.name }}/build
          mkdir ${{ github.event.repository.name }}/build
          west build \
            --board ${{ matrix.boards.boardname }} \
            --pristine=always ${{ github.event.repository.name }} \
            --build-dir ${{ github.event.repository.name }}/build \
            -- \
            -DNCS_TOOLCHAIN_VERSION=NONE \
            -DBOARD_ROOT=../${{ github.event.repository.name }}
          mv ${{ github.event.repository.name }}/build/${{ github.event.repository.name }}/zephyr/zephyr.${{ matrix.boards.fileformat }} Releases/${{ matrix.boards.filename }}.${{ matrix.boards.fileformat }}

      - name: 💾 Upload Artifact - ${{ matrix.boards.boardname }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.boards.filename }}.${{ matrix.boards.fileformat }}
          path: zephyr-workspace/Releases/${{ matrix.boards.filename }}.${{ matrix.boards.fileformat }}
